#!/usr/bin/env bash
###############################################################################
# Lenskart Retail Intelligence — One-Command Cloud Installer
#
# Paste this on a fresh Ubuntu 22.04+ server (DigitalOcean, AWS, Hetzner, etc.):
#
#   curl -sSL https://raw.githubusercontent.com/ailenskart/inventory/claude/setup-lenskart-monorepo-kZdMi/scripts/cloud-install.sh | bash
#
# Or if you already cloned the repo:
#
#   bash scripts/cloud-install.sh
#
# What it does:
#   1. Installs Docker if missing
#   2. Clones the repo (if not already in it)
#   3. Creates .env with secure random passwords
#   4. Builds and starts all services
#   5. Prints URLs when ready
#
# Requirements: Ubuntu 22.04+, 4GB RAM, 20GB disk
###############################################################################

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${BLUE}[i]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }

REPO_URL="https://github.com/ailenskart/inventory.git"
BRANCH="claude/setup-lenskart-monorepo-kZdMi"
INSTALL_DIR="/opt/lenskart"

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   Lenskart Retail Intelligence — Cloud Installer         ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Check system ─────────────────────────────────────────────────────

info "Checking system requirements..."

# Check RAM
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
if [ "$TOTAL_RAM_MB" -lt 3500 ]; then
    warn "Only ${TOTAL_RAM_MB}MB RAM detected. Recommended: 4096MB+"
    warn "The system may run slowly. Consider upgrading your server."
fi

# Check disk
AVAIL_DISK_GB=$(df -BG / | awk 'NR==2{print int($4)}')
if [ "$AVAIL_DISK_GB" -lt 15 ]; then
    err "Only ${AVAIL_DISK_GB}GB disk available. Need at least 15GB."
    exit 1
fi

log "System: ${TOTAL_RAM_MB}MB RAM, ${AVAIL_DISK_GB}GB disk available"

# ── Step 2: Install Docker ───────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log "Docker installed"
else
    log "Docker already installed: $(docker --version | head -1)"
fi

if ! docker compose version &>/dev/null; then
    info "Installing Docker Compose plugin..."
    apt-get update -qq && apt-get install -y -qq docker-compose-plugin
    log "Docker Compose installed"
else
    log "Docker Compose available: $(docker compose version)"
fi

# ── Step 3: Clone repo ──────────────────────────────────────────────────────

if [ -f "docker-compose.prod.yml" ] && [ -f "Dockerfile" ]; then
    # Already in the repo directory
    INSTALL_DIR="$(pwd)"
    log "Already in project directory: $INSTALL_DIR"
elif [ -d "$INSTALL_DIR" ] && [ -f "$INSTALL_DIR/docker-compose.prod.yml" ]; then
    log "Project already cloned at $INSTALL_DIR"
else
    info "Cloning repository..."
    git clone --branch "$BRANCH" --single-branch "$REPO_URL" "$INSTALL_DIR" 2>/dev/null || {
        # If clone fails (private repo), check if we're already in the repo
        if [ -f "pyproject.toml" ]; then
            INSTALL_DIR="$(pwd)"
            warn "Could not clone from GitHub. Using current directory."
        else
            err "Failed to clone repository. Make sure you have access."
            err "Alternative: git clone <your-repo-url> $INSTALL_DIR"
            exit 1
        fi
    }
    log "Repository cloned to $INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── Step 4: Generate .env with secure passwords ─────────────────────────────

if [ ! -f ".env" ]; then
    info "Generating .env with secure passwords..."

    PG_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
    MINIO_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

    cat > .env <<ENVEOF
# Auto-generated by cloud-install.sh on $(date -Iseconds)
POSTGRES_USER=lenskart
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=lenskart_retail
MINIO_ROOT_USER=lenskart
MINIO_ROOT_PASSWORD=${MINIO_PASS}
LENSKART_DB_PATH=/app/data/dev.duckdb
MLFLOW_TRACKING_URI=http://mlflow:5000
DAGSTER_HOME=/app/dagster_home
ENVEOF

    chmod 600 .env
    log "Created .env with secure passwords"
else
    log ".env already exists, keeping it"
fi

# ── Step 5: Open firewall ───────────────────────────────────────────────────

if command -v ufw &>/dev/null; then
    info "Configuring firewall..."
    ufw allow 80/tcp  >/dev/null 2>&1 || true
    ufw allow 443/tcp >/dev/null 2>&1 || true
    ufw allow 22/tcp  >/dev/null 2>&1 || true
    log "Firewall: ports 80, 443, 22 open"
fi

# ── Step 6: Build and start ─────────────────────────────────────────────────

info "Building Docker images (this takes 5-10 minutes on first run)..."
docker compose -f docker-compose.prod.yml build --quiet 2>&1 | tail -5

info "Starting all services..."
docker compose -f docker-compose.prod.yml up -d

# ── Step 7: Wait for bootstrap + API health ──────────────────────────────────

info "Running data bootstrap (generating data, running dbt)..."
info "This takes 3-8 minutes on first run. Be patient..."

# Wait for bootstrap to finish
WAIT=0
MAX_WAIT=600  # 10 minutes
while [ $WAIT -lt $MAX_WAIT ]; do
    STATUS=$(docker inspect --format='{{.State.Status}}' lenskart-bootstrap 2>/dev/null || echo "missing")
    if [ "$STATUS" = "exited" ]; then
        EXIT_CODE=$(docker inspect --format='{{.State.ExitCode}}' lenskart-bootstrap 2>/dev/null || echo "1")
        if [ "$EXIT_CODE" = "0" ]; then
            log "Data bootstrap completed successfully"
            break
        else
            err "Bootstrap failed (exit code $EXIT_CODE). Check logs:"
            err "  docker compose -f docker-compose.prod.yml logs bootstrap"
            exit 1
        fi
    fi
    if [ $((WAIT % 30)) -eq 0 ] && [ $WAIT -gt 0 ]; then
        info "Still bootstrapping... ($((WAIT/60))m elapsed)"
    fi
    sleep 5
    WAIT=$((WAIT + 5))
done

if [ $WAIT -ge $MAX_WAIT ]; then
    warn "Bootstrap is taking longer than expected. Check:"
    warn "  docker compose -f docker-compose.prod.yml logs -f bootstrap"
fi

# Wait for API
info "Waiting for API to come up..."
RETRIES=0
while [ $RETRIES -lt 30 ]; do
    if curl -sf http://localhost:8000/health >/dev/null 2>&1; then
        break
    fi
    RETRIES=$((RETRIES + 1))
    sleep 3
done

# ── Step 8: Detect public IP ─────────────────────────────────────────────────

PUBLIC_IP=$(curl -s --max-time 5 http://checkip.amazonaws.com 2>/dev/null || \
            curl -s --max-time 5 http://ifconfig.me 2>/dev/null || \
            hostname -I | awk '{print $1}')

# ── Step 9: Final status ─────────────────────────────────────────────────────

echo ""
echo ""

if curl -sf http://localhost:8000/health >/dev/null 2>&1; then
    echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║            INSTALLATION SUCCESSFUL!                       ║${NC}"
    echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${BOLD}Your platform is live at:${NC}"
    echo ""
    echo -e "  ${BLUE}Swagger UI (API Explorer):${NC}  http://${PUBLIC_IP}/docs"
    echo -e "  ${BLUE}Control Tower:${NC}              http://${PUBLIC_IP}/api/v1/control-tower/summary"
    echo -e "  ${BLUE}Dagster (Pipelines):${NC}        http://${PUBLIC_IP}:3000"
    echo -e "  ${BLUE}MLflow (Experiments):${NC}       http://${PUBLIC_IP}:5001"
    echo -e "  ${BLUE}MinIO (Storage):${NC}            http://${PUBLIC_IP}:9001"
    echo ""
    echo -e "  ${BOLD}Try these API calls:${NC}"
    echo ""
    echo -e "  curl http://${PUBLIC_IP}/api/v1/control-tower/summary"
    echo -e "  curl http://${PUBLIC_IP}/api/v1/lifecycle/sku/SKU00001"
    echo -e "  curl http://${PUBLIC_IP}/api/v1/vendors/scorecards"
    echo -e "  curl http://${PUBLIC_IP}/api/v1/assortment/scenarios"
    echo ""
    echo -e "  ${BOLD}To add HTTPS with your domain:${NC}"
    echo ""
    echo -e "  1. Point your domain DNS A record → ${PUBLIC_IP}"
    echo -e "  2. Run: ./scripts/deploy.sh ssl yourdomain.com"
    echo ""
    echo -e "  ${BOLD}Management commands:${NC}"
    echo ""
    echo -e "  cd ${INSTALL_DIR}"
    echo -e "  ./scripts/deploy.sh status     # Check health"
    echo -e "  ./scripts/deploy.sh logs api   # View API logs"
    echo -e "  ./scripts/deploy.sh stop       # Stop everything"
    echo -e "  ./scripts/deploy.sh update     # Pull latest + redeploy"
    echo ""
else
    echo -e "${YELLOW}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}${BOLD}║   SERVICES STARTING — API NOT READY YET                  ║${NC}"
    echo -e "${YELLOW}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  The data bootstrap may still be running."
    echo -e "  Wait a few minutes, then check:"
    echo ""
    echo -e "  docker compose -f docker-compose.prod.yml ps"
    echo -e "  docker compose -f docker-compose.prod.yml logs -f api"
    echo ""
    echo -e "  Once ready, open: http://${PUBLIC_IP}/docs"
    echo ""
fi
